### ISSUE TITLE
Increase in EC2 throttling failures.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/mismi#196]
Since early last week there has been a significant increase in RequestLimitExceeded failures (quickly too - indicating little to no back-off) - I have a suspicious that the retry handler is missing these again, or something else "bad" is happening.

```
Service error: Abbreviation: EC2, Status code: 503, Status message: Service Unavailable, Error: EC2Error {_errRequestID = "66bcce4c-261f-4591-8988-36fdfa541b5f", _errErrors = List1 {list1 = Message {_msgCode = Just (ErrorCode "RequestLimitExceeded"), _msgMessage = "Request limit exceeded."} :| []}}
``` 

Seeing this in power/sanction/bakery/hydra.

**Comment by EduardSergeev** [comment]
Could it be because of the default retry setting in `amazonka` being too "aggressive"? All our apps use EC2 directly and if I am reading the code correctly [here](https://github.com/brendanhay/amazonka/blob/develop/amazonka-ec2/gen/Network/AWS/EC2/Types.hs#L1690-L1695) and [here](https://github.com/brendanhay/amazonka/blob/develop/amazonka/src/Network/AWS/Internal/HTTP.hs#L159-L166) EC2 starts with 50ms and makes 5 attempts with maximum delay == 800ms. Too quick or is it ok?

**Comment by markhibberd** [comment]
Too quick I think. Probably stat with 200ms, with maybe 5 or 8, by default.

**Comment by nhibberd** [comment]
This has been fixed now --
http://hackage.haskell.org/package/amazonka-ec2-1.3.2/docs/src/Network-AWS-EC2-Types.html#eC2
with https://github.com/brendanhay/amazonka/pull/229
