### ISSUE TITLE
Ec2 - Add security group id lookup

### ISSUE THREAD

**Issue by nhibberd** [ambiata/mismi#249]
See sanction / slate / seesaw

**Comment by EduardSergeev** [comment]
@nhibberd if you happy with [slate's implementation](https://github.com/ambiata/slate/blob/master/slate-core/src/Slate/Commands.hs#L271-L277) I can move it to Mismi.EC2.. Otherwise there is [sanction's](https://github.com/ambiata/sanction/blob/master/src/Sanction/Internal/Instance/DescribeSecurityGroups.hs#L20-L26) Take you pick.

**Comment by nhibberd** [comment]
The pre-filter is definitely better, would be nice to have a maybe name or two implementations so people don't get stuck downstream

**Comment by EduardSergeev** [comment]
Interface from `sanction`, implementation from `slate`? :) I was not sure if it would be useful to allow lookup of a set of security groups..

**Comment by nhibberd** [comment]
Yeah that's a good idea, input can always be a list

**Comment by EduardSergeev** [comment]
> Yeah that's a good idea, input can always be a list

But the interface becomes awkward. What would return type of this version? Property list? Map? `[Maybe SecurityGroupName]`? Meanwhile: https://github.com/ambiata/mismi/pull/250

**Comment by nhibberd** [comment]
Could create a data type and wrap a map or something
